Repository frctl/fractal, pull requests merged in 2018-09, with the labels that each got.

#462 Update mocha and vorpal
  package-lock.json
  package.json
Labels: [area] internals, v1.x

#468 Perform all minor/patch dependency updates.
  package-lock.json
  package.json
Labels: security

#458 Remove ShellJS dependency.
  package-lock.json
  package.json
  src/cli/commands/new.js
  src/core/shell.js
  test/core.shell.js
Labels: [area] cli, [type] internal/refactor, security
